[package]
name = "chance_the_wrapper"
version = "0.0.0"
authors = ["Niklas Sauter <niklas@n1ks.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
